name: PR Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'python/**'

jobs:
  python-tests:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - id: changes
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42 # v1

      - name: Set up Python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: '3.8'  # Specify the Python version here

      - name: Set Environment Variable
        run: echo "TEST_ANSWER=${{ secrets.TEST_ANSWER }}" >> $GITHUB_ENV

      - name: Run Python Tests
        run: |
          cd python
          python3 solution.test.py
