name: PR Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ruby/**'

jobs:
  ruby-tests:
    name: Run Ruby Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Setup Ruby
        uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Set Environment Variable
        run: echo "TEST_ANSWER=${{ secrets.TEST_ANSWER }}" >> $GITHUB_ENV

      - run: cd ruby && bundle install
      - run: cd ruby && rspec solution.test.rb
