name: PR Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ruby/**'

jobs:
  ruby-tests:
    name: Run Ruby Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Ruby
        uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.235.0
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Set Environment Variable
        run: echo "TEST_ANSWER=${{ secrets.TEST_ANSWER }}" >> $GITHUB_ENV

      - run: cd ruby && bundle install
      - run: cd ruby && rspec solution.test.rb
