name: PR Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'typescript/**'

jobs:
  typescript-tests:
    name: Run TypeScript Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - id: changes
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42 # v1

      - name: Setup Node.js
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '14'

      - name: Set Environment Variable
        run: echo "TEST_ANSWER=${{ secrets.TEST_ANSWER }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd typescript
          npm install

      - name: Run TypeScript Tests
        run: |
          cd typescript
          npm test
